### ISSUE TITLE
Wavi - Onboarding - Scan QR Code not working

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#201]
**Describe the bug**
I tried to activate a new atsign ```@32clever68``` from the dashboard at around 8:37 PT on sept 27th. Once the QR code had been generated, I used the current version of wavi (from testflight) and tried the "Scan QR code" option. I scanned the QR Code and the screen was spinning for over 10 minutes until I cancelled the process. 

**To Reproduce**
1. Activate an atsign from the dashboard
2. Use Scan QR Code to scan the generated QR code

**Expected behavior**
The atsign activation should be successful.

**Smartphone (please complete the following information):**
 - iphone
 - iOS 15
 

**Were you using an @‎application when the bug was found?**
  - Wavi 0.15.7 (47)

**Comment by charannnreddy** [comment]
Fixed the issue and published latest onboarding package to the pub dev(v3.0.3)
Pr : https://github.com/atsign-foundation/at_widgets/pull/213

**Comment by tinashe404** [comment]
This issue isn still happening in the apps. example Wavi. linked to https://github.com/atsign-foundation/at_client_sdk/issues/1609

**Comment by charannnreddy** [comment]
@tinashe404 If an atsign is already activated, then the qr won't work. We can only use qr's of the deactivated atsigns.

**Comment by tinashe404** [comment]
@charannnreddy this had been failing on atsigns that were in the process of being activated. Will test with the new version.

**Comment by charannnreddy** [comment]
@tinashe404 Did you get a chance to test with the new version?

**Comment by tinashe404** [comment]
@charannnreddy the QR Code scanner is working now  (was able to activate the atsign) however when you press Scan QR Code, the camera square is not appearing in the widget correctly. Please see screenshot below.
![IMG_5661](https://user-images.githubusercontent.com/69275762/139683813-77b2e075-f0b8-4545-913c-8ed264334d5d.PNG)

**Comment by tinashe404** [comment]
Hi.. Any update on this issue where the camera screen is not being displayed inside the UI element correctly?

**Comment by tinashe404** [comment]
This is now fixed
